weHelp/accounts/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name='signup'),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^my_posts/$', views.adult_page, name="my_posts"),
    url(r'^checking/$', views.check, name='check_page'),
    url(r'^adult_login/$', views.adult_login, name='Alogin'),
    url(r'^young_login/$', views.young_login, name='Ylogin'),
    url(r'^helper/$', views.young_hompage, name='young_homepage'),
    url(r'^saved_posts/$', views.young_saved_posts, name='saved_posts'),
    path('success/<str:pk>/', views.got_helped, name='got_helped'),
    url(r'^admin_homepage/$', views.admin_homepage, name="admin_homepage"),
    url(r'^admin_young/$', views.admin_young, name="admin_young"),
    url(r'^admin_adult/$', views.admin_adult, name="admin_adult"),
    url(r'^admin_posts/$', views.admin_posts, name="admin_post"),
    path('delete_young/<str:pk>/', views.delete_young, name='delete_young'),
    path('delete_adult/<str:pk>/', views.delete_adult, name='delete_adult'),
    path('delete_post/<str:pk>/', views.delete_post, name='delete_post'),
    path('success_check/<str:pk>/',
         views.admin_got_helped, name='admin_got_helped'),
]

weHelp/accounts/templates/accounts/Alogin.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="form-container">
    <form action="{% url 'accounts:Alogin' %}" method='POST'>
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="הרשם">
    </form>
</div>
<style>
    body {
        width: 100vw;
        height: 100vh;
        margin: 0;
        background-image: url(../../../static/img/bg-image.jpg);
        background-size: cover;
        background-position: 50%;
        background-repeat: no-repeat;
        overflow: hidden;
    }
    form{
        display: flex;
        flex-direction: column;
        width: 400px;
        margin: 0 auto;
    }
    .form-container{
        display: flex;
        align-items: center;
        justify-content: center;
        height: 85vh;
    }
</style>
{% endblock %}

weHelp/accounts/templates/accounts/Ylogin.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="form-container">
    <form action="{% url 'accounts:Ylogin' %}" method='POST'>
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="הרשם">
    </form>
</div>
<style>
    body {
        width: 100vw;
        height: 100vh;
        margin: 0;
        background-image: url(../../../static/img/bg-image.jpg);
        background-size: cover;
        background-position: 50%;
        background-repeat: no-repeat;
        overflow: hidden;
    }
    form{
        display: flex;
        flex-direction: column;
        width: 400px;
        margin: 0 auto;
    }
    .form-container{
        display: flex;
        align-items: center;
        justify-content: center;
        height: 85vh;
    }
</style>
{% endblock %}

weHelp/accounts/templates/accounts/admin_adults.html
{% extends 'base_layout.html' %}

{% block content %}
<div style="text-align: center;">
    <h2>יוזרים מבוגרים</h2>
</div>
<div class="row">
    {% for adult in adults %}
    <div class="col-sm-6">
        <div class="card" style="margin-bottom: 20px;">
            <div class="card-body">
                <h5 class="card-title" style="text-align: center;">{{ adult.name }}</h5>
                <p class="card-text" style="text-align: center;">גיל {{adult.age}} גר/ה ב{{adult.city}}</p>
                <div style="text-align: center;">
                    <a href="https://wa.me/"
                        onclick="location.href=this.href+remove_plus('{{adult.phone}}'); return false;"
                        class="btn btn-primary"><i class="fab fa-whatsapp"></i>
                        שלח הודעה</a>
                    <a href="tel:" onclick="location.href=this.href+change_phone('{{adult.phone}}');return false;"
                        class="btn btn-primary"><i class="fas fa-phone-alt"></i>
                        התקשר</a>
                    <a href="{% url 'accounts:delete_adult' adult.id %}" class="btn btn-danger">מחק יוזר</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<script>
    function change_phone(x) {
        clean = x.slice(-9);
        newnum = ''.concat('0', clean);
        console.log(newnum);
        return newnum;
    }

    function remove_plus(x) {
        console.log(x);
        k = x.slice(-12);
        console.log(k);
        return k;
    }
</script>
{% endblock %}

weHelp/accounts/templates/accounts/admin_homepage.html
{% extends 'base_layout.html' %}
{% load static %}

{% block content %}
<div style="text-align: center;">
    <h1>דוחות לאדמין</h1>
</div>
<div class="container" style="display: flex;">
    <div
        style="width: 18rem;margin: 10px; border-style: solid; border-radius: 10px; border-width: 2px; border-color:rgb(212, 212, 212);">
        <img src="{% static 'img/old_man.png' %}" class="card-img-top" alt="...">
        <div style="text-align: center;">
            <p class="card-text">מספר המבוגרים באתר:</p>
            <h4> {{ adults }}</h4>
        </div>
    </div>
    <div
        style="width: 18rem;margin: 10px; border-style: solid; border-radius: 10px; border-width: 2px; border-color:rgb(212, 212, 212);">
        <img src="{% static 'img/group-happy-young-people-hand-up-13817553.jpg' %}" class="card-img-top" alt="...">
        <div class="card-body" style="text-align: center;">
            <p class="card-text">מספר הצעירים באתר:</p>
            <h4> {{ youngs }}</h4>
        </div>
    </div>
    <div
        style="width: 18rem;margin: 10px; border-style: solid; border-radius: 10px; border-width: 2px; border-color:rgb(212, 212, 212);">
        <img src="{% static 'img/posts.png' %}" class="card-img-top" alt="...">
        <div class="card-body" style="text-align: center;">
            <p class="card-text">מספר הפוסטים באתר:</p>
            <h4> {{ posts }}</h4>
        </div>
    </div>
    <div
        style="width: 18rem;margin: 10px; border-style: solid; border-radius: 10px; border-width: 2px; border-color:rgb(212, 212, 212);">
        <img src="{% static 'img/v.jfif' %}" class="card-img-top" alt="...">
        <div class="card-body" style="text-align: center;">
            <p class="card-text">מספר הפוסטים שטופלו:</p>
            <h4> {{ got_help }}</h4>
        </div>
    </div>
    <div
        style="width: 18rem;margin: 10px; border-style: solid; border-radius: 10px; border-width: 2px; border-color:rgb(212, 212, 212);">
        <img src="{% static 'img/x.png' %}" class="card-img-top" alt="...">
        <div class="card-body" style="text-align: center;">
            <p class="card-text">מספר הפוסטים שעוד לא טופלו:</p>
            <h4> {{ yet }}</h4>
        </div>
    </div>
</div>
{% endblock %}

weHelp/accounts/templates/accounts/admin_posts.html
{% extends 'base_layout.html' %}

{% block content %}
<div style="text-align: center; ">
    <h2>:פוסטים באתר</h2>
</div>
<div>
    {% for post in posts %}
    <div class="card text-center"
        style="margin-left: 10%;margin-right: 10%;margin-top: 15px;margin-bottom: 15px; border-radius: 10px; width: 80%; border: 1px solid rgb(30, 172, 253);box-shadow: 5px 10px 18px #888888;">
        <div class="card-header">
            <div class="row align-items-start">
                <div class="col">
                    {% if post.status == False %}
                    <a href="{% url 'accounts:admin_got_helped' post.id %}" class="btn btn-primary">'סמן כ'טופל</a>
                    {% else %}
                    <a href="{% url 'accounts:admin_got_helped' post.id %}" class="btn btn-primary">'בטל סימון
                        כ'טופל</a>
                    {% endif %}
                    <a href="{% url 'accounts:delete_post' post.id %}" class="btn btn-danger">מחק פוסט</a>

                </div>
                <div class="col">
                    <h4>{{post.author.name}}</h4>
                </div>
                <div class="col">
                    {% if post.status == False %}
                    <p style="margin-bottom: 0;">זקוק לטיפול <i class="far fa-circle" style="color: red;"></i></p>
                    {% else %}
                    <p style="margin-bottom: 0;">טופל <i class="fas fa-circle" style="color: greenyellow;"></i></p>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="card-body">
            <p class="card-text">{{post.title}}</p>
            <p class="card-text">{{post.text}}</p>
            <p class="card-text">מיקום: {{post.city}}</p>
            <p class="card-text">צריך סיוע ב{{post.selected_help}}</p>

            <div class="row justify-content-md-center">
                <a href="https://wa.me/" onclick="location.href=this.href+remove_plus('{{post.phone}}'); return false;"
                    class="btn btn-primary col col-lg-2"><i class="fab fa-whatsapp"></i>
                    שלח הודעה</a>
                <p class="col col-lg-2"></p>
                <a href="tel:" onclick="location.href=this.href+change_phone('{{post.phone}}');return false;" class="btn btn-primary col
                    col-lg-2"><i class="fas fa-phone-alt"></i>
                    התקשר</a>
            </div>

        </div>
        <div class="card-footer text-muted">
            {{post.date}} :תאריך פרסום
        </div>
    </div>
    {% endfor %}
    <!-- -->
</div>
<script>
    function change_phone(x) {
        clean = x.slice(-9);
        newnum = ''.concat('0', clean);
        console.log(newnum);
        return newnum;
    }

    function remove_plus(x) {
        console.log(x);
        k = x.slice(-12);
        console.log(k);
        return k;
    }
</script>
{% endblock %}

weHelp/accounts/templates/accounts/admin_youngs.html
{% extends 'base_layout.html' %}

{% block content %}
<div style="text-align: center;">
    <h2>יוזרים צעירים</h2>
</div>
<div class="row">
    {% for young in youngs %}
    <div class="col-sm-6">
        <div class="card" style="margin-bottom: 20px;">
            <div class="card-body">
                <h5 class="card-title" style="text-align: center;">{{ young.name }}</h5>
                <p class="card-text" style="text-align: center;">גיל {{young.age}} גר/ה ב{{young.city}}</p>
                <div style="text-align: center;">
                    <a href="https://wa.me/"
                        onclick="location.href=this.href+remove_plus('{{young.phone}}'); return false;"
                        class="btn btn-primary"><i class="fab fa-whatsapp"></i>
                        שלח הודעה</a>
                    <a href="tel:" onclick="location.href=this.href+change_phone('{{young.phone}}');return false;"
                        class="btn btn-primary"><i class="fas fa-phone-alt"></i>
                        התקשר</a>
                    <a href="{% url 'accounts:delete_young' young.id %}" class="btn btn-danger">מחק יוזר</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<script>
    function change_phone(x) {
        clean = x.slice(-9);
        newnum = ''.concat('0', clean);
        console.log(newnum);
        return newnum;
    }

    function remove_plus(x) {
        console.log(x);
        k = x.slice(-12);
        console.log(k);
        return k;
    }
</script>
{% endblock %}

weHelp/accounts/templates/accounts/ask_for_kind.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="ask">
    <div class="h"<h2>:בחר סוג משתמש</h2></div>
    <div class="btn-group" role="group" aria-label="Basic example">
        <a style="font-size:30px" href="{% url 'accounts:Alogin' %}" class="btn btn-primary stretched-link">מבוגר</a>
        <a style="font-size:30px" href="{% url 'accounts:Ylogin' %}" class="btn btn-primary stretched-link">צעיר</a>
    </div>
</div>
<style>
    body {
          width: 100vw;
          height: 100vh;
          margin: 0;
          background-image: url(../../../static/img/bg-image.jpg);
          background-size: cover;
          background-position: 50%;
          background-repeat: no-repeat;
          overflow: hidden;
      }
      .ask{
        justify-content: center;
        text-align: center;
      }
      .h{
        font-size: 60px;
      }
  </style>
{% endblock %}

weHelp/accounts/templates/accounts/index.html
{% extends 'base_layout.html' %}
{% load static %}

{% block content %}


<div class="container">
    <h1>
        אתר חברתי שמטרתו לקשר בין אנשים מבוגרים המתקשים לבצע פעולות יום יומיות, לבין אנשים המוכנים לעזור על מנת להפוך את חייהם לפשוטים ונגישים יותר במהלך תקופת הקורונה.
    </h1>
    <div class="content">
                האתר WeHelp  הוקם במטרה לקשר בין אנשים מבוגרים הזקוקים לעזרה בפעולות היום יום לבין אנשים המעוניינים לעזור להם. 
    במהלך תקופת משבר הקורונה, מבוגרים רבים פחדו לצאת החוצה מחשש להדבק בנגיף, דבר שהוביל לריחוק חברתי שיצר בדידות, מחסור במצרכים בסיסיים בבית ואי יכולת לצאת לחדש מאגרים ותיחזוק שוטף שלא נעשה מהחשש להכניס זרים הביתה.
    בין מגבלות הסגר, אוכלוסיה מבוגרת הוגדרה כאוכלוסיה בסיכון והוגבלה תנועה במרחב הציבורי. 
    האתר שלנו בא לתת מענה לבעיות המתוארות לעיל בכך שיחבר אנשים הרתומים לעזור ולסייע לאוכלוסיה המבוגרת, לבין המבוגרים כך שיוכלו שיעזרו למבוגרים בכל מטלות היום יום ובהפגת הבדידות שנכפתה עליהם.
    נבנה אתר שאליו יוכלו להיכנס מבוגרים, וצעירים המעוניינים לתרום. האתר יהיה מבוסס בלוג, יווצרו יוזרים שיוכלו להתקשר בניהם. יוזר הנבנה בתור מבוגר, תהיה באפשרותו לבקש עזרה בכל מיני תחומים, ויוזר הנותן עזרה ("צעיר") יוכל לתת מענה עבור פניות של מבוגרים.
    </div>
</div>

{% endblock %}

weHelp/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}
{% load static %}

{% block content %}
<!---->
<style>
    body {
        width: 100vw;
        height: 100vh;
        margin: 0;
        background-image: url(../../../static/img/bg-image.jpg);
        background-size: cover;
        background-position: 50%;
        background-repeat: no-repeat;
        overflow: hidden;
    }
    .wave {
        position: fixed;
        bottom: 0;
        left: 0;
        height: 100%;
        z-index: -1;
    }

    /* .container {
        width: 100vw;
        height: 100vh;
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        grid-gap: 7rem;
        padding: 0 2rem;
    } */

    .img {
        display: flex;
        justify-content: flex-end;
        align-items: center;
    }

    .login-content {
        display: flex;
        justify-content: center;
        text-align: center;

    }
    .img img {
        width: 500px;
    }

    form {
        width: 360px;
    }

    .login-content img {
        height: 100px;
        /* display: block;
        margin-left: auto;
        margin-right: auto;
        width: 40%; */
        }

    .login-content h2 {
        margin: 15px 0;
        color: #333;
        text-transform: uppercase;
        font-size: 2.9rem;
    }

    .login-content .input-div {
        position: relative;
        display: grid;
        grid-template-columns: 7% 93%;
        margin: 25px 0;
        padding: 5px 0;
        border-bottom: 2px solid #d9d9d9;
    }

    .login-content .input-div.one {
        margin-top: 0;
    }

    .i {
        color: #d9d9d9;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .i i {
        transition: .3s;
    }

    .input-div>div {
        position: relative;
        height: 45px;
    }

    .input-div>div>h5 {
        position: absolute;
        left: 10px;
        top: 50%;
        transform: translateY(-50%);
        color: #999;
        font-size: 18px;
        transition: .3s;
    }

    .input-div:before,
    .input-div:after {
        content: '';
        position: absolute;
        bottom: -2px;
        width: 0%;
        height: 2px;
        background-color: #38d39f;
        transition: .4s;
    }

    .input-div:before {
        right: 50%;
    }

    .input-div:after {
        left: 50%;
    }

    .input-div.focus:before,
    .input-div.focus:after {
        width: 50%;
    }

    .input-div.focus>div>h5 {
        top: -5px;
        font-size: 15px;
    }

    .input-div.focus>.i>i {
        color: #38d39f;
    }

    .input-div>div>input {
        position: absolute;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        border: none;
        outline: none;
        background: none;
        padding: 0.5rem 0.7rem;
        font-size: 1.2rem;
        color: #555;
        font-family: 'poppins', sans-serif;
    }

    .input-div.pass {
        margin-bottom: 4px;
    }

    .btn {
        display: block;
        width: 100%;
        height: 50px;
        border-radius: 25px;
        outline: none;
        border: none;
        background-image: linear-gradient(to right, #32be8f, #38d39f, #32be8f);
        background-size: 200%;
        font-size: 1.2rem;
        color: #fff;
        font-family: 'Poppins', sans-serif;
        text-transform: uppercase;
        margin: 1rem 0;
        cursor: pointer;
        transition: .5s;
    }

    .btn:hover {
        background-position: right;
    }


    @media screen and (max-width: 1050px) {
        .container {
            grid-gap: 5rem;
        }
    }

    @media screen and (max-width: 1000px) {
        form {
            width: 290px;
        }

        .login-content h2 {
            font-size: 2.4rem;
            margin: 8px 0;
        }

        .img img {
            width: 400px;
        }
    }

    @media screen and (max-width: 900px) {
        .container {
            grid-template-columns: 1fr;
        }

        .img {
            display: none;
        }

        /* .wave {
            display: none;
        } */

        .login-content {
            justify-content: center;
        }
    }
</style>
<!-- <img class="wave" src="{% static 'img/wave.png' %}">
<div class="container">
    <div class="img">
        <img src="{% static 'img\bg.svg' %}">
    </div> -->
    <div class="login-content">
        <form action="{% url 'accounts:login' %}" method='POST'>
            {% csrf_token %}
            <img src="{% static 'img/avatar.svg' %}">
            <h2 class="title">התחבר</h2>
            <div class="input-div one">
                <div class="i">
                    <i class="fas fa-user"></i>
                </div>
                <div class="div">
                    {{ form.username }}
                </div>
            </div>
            <div class="input-div pass">
                <div class="i">
                    <i class="fas fa-lock"></i>
                </div>
                <div class="div">
                    {{ form.password }}
                </div>
            </div>
            <input type="submit" class="btn" value="התחבר">
    </div>
    </form>
</div>
</div>

<script>
    const inputs = document.querySelectorAll(".input");


    function addcl() {
        let parent = this.parentNode.parentNode;
        parent.classList.add("focus");
    }

    function remcl() {
        let parent = this.parentNode.parentNode;
        if (this.value == "") {
            parent.classList.remove("focus");
        }
    }


    inputs.forEach(input => {
        input.addEventListener("focus", addcl);
        input.addEventListener("blur", remcl);
    });
</script>
{% endblock %}

weHelp/accounts/templates/accounts/saved_posts.html
{% extends 'base_layout.html' %}

{% block content %}
<div style="text-align: center; ">
    <h2>:פוסטים ששמרת</h2>
</div>
<div>
    {% for post in posts %}
    <div class="card text-center"
        style="margin-left: 10%;margin-right: 10%;margin-top: 15px;margin-bottom: 15px; border-radius: 10px; width: 80%; border: 1px solid rgb(30, 172, 253);box-shadow: 5px 10px 18px #888888;">
        <div class="card-header">
            <div class="row align-items-start">
                <div class="col">
                    {% if post.status == False %}
                    <a href="{% url 'accounts:got_helped' post.id %}" class="btn btn-primary btn-sm">'סמן כ'טופל</a>
                    {% else %}
                    <a href="{% url 'accounts:got_helped' post.id %}" class="btn btn-primary btn-sm">'בטל סימון
                        כ'טופל</a>
                    {% endif %}
                    <a href="https://wa.me/+972533404508" class="btn btn-danger" style="height: 32px;">דווח על פוסט</a>
                </div>
                <div class="col">
                    <h4>{{post.author.name}}</h4>
                </div>
                <div class="col">
                    {% if post.status == False %}
                    <p style="margin-bottom: 0;">זקוק לטיפול <i class="far fa-circle" style="color: red;"></i></p>
                    {% else %}
                    <p style="margin-bottom: 0;">טופל <i class="fas fa-circle" style="color: greenyellow;"></i></p>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="card-body">
            <p class="card-text">{{post.title}}</p>
            <p class="card-text">{{post.text}}</p>
            <p class="card-text">מיקום: {{post.city}}</p>
            <p class="card-text">צריך סיוע ב{{post.selected_help}}</p>

            <div class="row justify-content-md-center">
                <a href="https://wa.me/" onclick="location.href=this.href+remove_plus('{{post.phone}}'); return false;"
                    class="btn btn-primary col col-lg-2"><i class="fab fa-whatsapp"></i>
                    שלח הודעה</a>
                <p class="col col-lg-2"></p>
                <a href="tel:" onclick="location.href=this.href+change_phone('{{post.phone}}');return false;" class="btn btn-primary col
                    col-lg-2"><i class="fas fa-phone-alt"></i>
                    התקשר</a>
            </div>

        </div>
        <div class="card-footer text-muted">
            {{post.date}} :תאריך פרסום
        </div>
    </div>
    {% endfor %}
    <!-- -->
</div>
<script>
    function change_phone(x) {
        clean = x.slice(-9);
        newnum = ''.concat('0', clean);
        console.log(newnum);
        return newnum;
    }

    function remove_plus(x) {
        console.log(x);
        k = x.slice(-12);
        console.log(k);
        return k;
    }
</script>
{% endblock %}

weHelp/accounts/templates/accounts/user.html
{% extends 'base_layout.html' %}

{% block content %}

<div style="text-align: center; ">
    <h2>:הבקשות שלך</h2>
</div>
<div>
    {% for post in posts %}
    <div class="card text-center"
        style="margin-left: 10%;margin-right: 10%;margin-top: 15px;margin-bottom: 15px; border-radius: 10px; width: 80%; border: 1px solid rgb(30, 172, 253);">
        <div class="card-header">
            <div class="row align-items-start">

                <div class="col">
                    <a href="{% url 'accounts:delete_post' post.id %}" class="btn btn-danger">מחק פוסט</a>
                </div>
                <div class="col">
                    {{post.author.name}}
                </div>
                <div class="col">
                    {% if post.status == False %}
                    <p style="margin-bottom: 0;">זקוק לטיפול <i class="far fa-circle" style="color: red;"></i></p>
                    {% else %}
                    <p style="margin-bottom: 0;">טופל <i class="fas fa-circle" style="color: greenyellow;"></i></p>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="card-body">
            <p class="card-text">{{post.title}}</p>
            <p class="card-text">{{post.text}}</p>
            <p class="card-text">מיקום: {{post.city}}</p>
            <p class="card-text">צריך סיוע ב{{post.selected_help}}</p>
            <div class="row justify-content-md-center">
                <a href="https://wa.me/" onclick="location.href=this.href+remove_plus('{{post.phone}}'); return false;"
                    class="btn btn-primary col col-lg-2"><i class="fab fa-whatsapp"></i>
                    שלח הודעה</a>
                <p class="col col-lg-2"></p>
                <a href="tel:" onclick="location.href=this.href+change_phone('{{post.phone}}');return false;" class="btn btn-primary col
                                col-lg-2"><i class="fas fa-phone-alt"></i>
                    התקשר</a>
            </div>
        </div>
        <div class="card-footer text-muted">
            {{post.date}} :תאריך פרסום
        </div>
    </div>
    {% endfor %}
</div>
<script>
    function change_phone(x) {
        clean = x.slice(-9);
        newnum = ''.concat('0', clean);
        console.log(newnum);
        return newnum;
    }

    function remove_plus(x) {
        console.log(x);
        k = x.slice(-12);
        console.log(k);
        return k;
    }
</script>

{% endblock %}

weHelp/accounts/templates/accounts/young_homepage.html
{% extends 'base_layout.html' %}
{% load static %}


{% block content %}
<div style="text-align: center; ">
    <h2>:אנשים הצריכים עזרה בסביבתך</h2>
</div>
<form method="get">
    <div
        style="margin-left: 15%; margin-right: 15%;padding: 5px; text-align: center; background-color: #e4e4e4; border-radius: 7px; padding: 5px;">
        <input class="form-control" type="text" placeholder="חיפוש לפי עיר" aria-label="default input example"
            name="city" style="margin-right: 10px;">
        <button class="btn btn-primary" type="submit" style="margin-top: 10px;">חפש</button>
    </div>
</form>
<div>
    {% for post in posts %}
    <div class="card text-center"
        style="margin-left: 10%;margin-right: 10%;margin-top: 15px;margin-bottom: 15px; border-radius: 10px; width: 80%; border: 1px solid rgb(30, 172, 253);box-shadow: 5px 10px 18px #888888;">
        <div class="card-header">
            <div class="row align-items-start">
                <div class="col">
                    <a class="btn btn-primary" href="{% url 'adultposts:current_post' post.id %}">שמור
                        פוסט</a>
                </div>
                <div class="col">
                    <h4>{{post.author.name}}</h4>
                </div>
                <div class="col">
                    {% if post.status == False %}
                    <p style="margin-bottom: 0;">זקוק לטיפול <i class="far fa-circle" style="color: red;"></i></p>
                    {% else %}
                    <p style="margin-bottom: 0;">טופל <i class="fas fa-circle" style="color: greenyellow;"></i></p>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="card-body">
            <p class="card-text">{{post.title}}</p>
            <p class="card-text">{{post.text}}</p>
            <p class="card-text">מיקום: {{post.city}}</p>
            <p class="card-text">צריך סיוע ב{{post.selected_help}}</p>
            <div class="row justify-content-md-center">
                <a href="https://wa.me/" onclick="location.href=this.href+remove_plus('{{post.phone}}'); return false;"
                    class="btn btn-primary col col-lg-2"><i class="fab fa-whatsapp"></i>
                    שלח הודעה</a>
                <p class="col col-lg-2"></p>
                <a href="tel:" onclick="location.href=this.href+change_phone('{{post.phone}}');return false;" class="btn btn-primary col
                                col-lg-2"><i class="fas fa-phone-alt"></i>
                    התקשר</a>
            </div>
        </div>
        <div class="card-footer text-muted">
            {{post.date}} :תאריך פרסום
        </div>
    </div>
    {% endfor %}
</div>

<script>
    function change_phone(x) {
        clean = x.slice(-9);
        newnum = ''.concat('0', clean);
        console.log(newnum);
        return newnum;
    }

    function remove_plus(x) {
        console.log(x);
        k = x.slice(-12);
        console.log(k);
        return k;
    }
</script>

{% endblock %}